---
name: WWW-Mechanize-Plugin-FollowMetaRedirect
version: 0.01
author:
  - 'Ryo Okamoto <ryo at aquahill dot net>'
abstract: Follows 'meta refresh' link
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::TokeParser: 0
  WWW::Mechanize: 0
build_requires:
  Test::More: 0
  Time::HiRes: 0
  URI: 0
provides:
  WWW::Mechanize::Plugin::FollowMetaRedirect:
    file: lib/WWW/Mechanize/Plugin/FollowMetaRedirect.pm
    version: 0.01
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
